I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 8, in script
    text_color  "#FF0000"
Exception: Sayer 'text_color' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 8, in script
    text_color  "#FF0000"
  File "C:\Users\DELL\Downloads\renpy-8.2.1-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "C:\Users\DELL\Downloads\renpy-8.2.1-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\DELL\Downloads\renpy-8.2.1-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'text_color' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
test1 1.0
Wed May  1 21:09:01 2024
